### PR TITLE
Composer support

### PR DESCRIPTION
**Pull request by pmill**
Added composer.json file for installs via packagist (https://packagist.org/). You guys will need to create an account on packagist and add this repository, this should allow installs via `composer require mediaburst/clockwork-php`.

### CODE REVIEW

**Comment by pmill** [comment]
Also, the change in this pull request is backwards compatible.

**Comment by tomgillett** [comment]
Is there any chance of this getting merged? I'd love to be able to load this via Composer without having to resort to horrible workarounds... 

Even if you don't want to submit to Packagist, allowing the project to contain the package.json would ensure that the dependency can be declared against the Github repo, i.e.
````
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/mediaburst/clockwork-php.git"
        }
    ],
````

**Comment by WiseAndy** [comment]
Thanks @tomgillett - Not sure why this hasn't been addressed yet. Will bring it up in Sprint planning and  see if we can get it merged.

**Comment by tomgillett** [comment]
Great! Thanks @WiseAndy.

**Comment by richardhj** [comment]
> Not sure why this hasn't been addressed yet.

Me neither.

**Comment by baychae** [comment]
👍

**Pull request closed without merging**
