### PR TITLE
Composer support

### LINKED ISSUE #1: Composer packaging?
Looks great! Any chance of re-working your code slightly to make incorporating it into [Composer](http://getcomposer.corg)-managed projects easier? (i.e. `composer.json` file, namespacing and PSR-0 class names)?

### PR DESCRIPTION
**Pull request by WiseAndy**
Support for composer, based heavily on the work by @weemen @pmill and @tomgillett in PR #2 and #7 Closes #1

### CODE REVIEW

**Review by weemen — COMMENTED** [review]
+93 -1052, that's a very good sign! If I would mention something then it would be missing unittests but maybe we should add them as a separate thing

**Comment by weemen** [comment]
@WiseAndy how is this code tested? :)

**Comment by WiseAndy** [comment]
@weemen Current manually tested for each release. Clearly not ideal, planning on introducing a set of unit tests in a subsequent release (across all our code wrappers)

**Review by JoeEcob — APPROVED** [review]
Looks good 👍

**Pull request merged**
